# Generated by Django 3.0.7 on 2021-07-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('symbol', models.CharField(max_length=24)),
                ('price', models.DecimalField(decimal_places=4, max_digits=11)),
            ],
        ),
    ]
